<?php

########################################################################
# Extension Manager/Repository config file for ext: "me_extsearch"
#
# Auto generated by Extension Builder 2012-11-06
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Indexed Search Extensions',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jan Maennig',
	'author_email' => 'jma@move-elevator.de',
	'author_company' => 'move elevator GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.1.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>