<?php

########################################################################
# Extension Manager/Repository config file for ext: "me_extsearch"
#
# Auto generated by Extension Builder 2012-11-05
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Delete Searchcache',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Jan Maennig',
    'author_email' => 'jma@move-elevator.de',
    'author_company' => 'move elevator GmbH',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.0.1',
    'constraints' => array(
        'depends' => array(
            'extbase' => '1.3',
            'fluid' => '1.3',
            'typo3' => '4.5',
            'scheduler' => ''
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
?>